services:
  backend:
    image: ankapieka/ecogeste-server
    ports:
      - 4000:4000
    volumes:
      - ./back/src:/app/src

  frontend:
    image: ankapieka/ecogeste
    ports:
      - 3000:3000
    volumes:
      - ./front/src:/app/src

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
