services:
  backend:
    image: ankapieka/ecogeste-server
    ports:
      - 4000:4000
    volumes:
      - ./back/src:/app/src

  frontend:
    image: ankapieka/ecogeste
    ports:
      - 3000:3000
    volumes:
      - ./front/src:/app/src

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  caddy:
    image: caddy:2.7.5
    restart: unless-stopped
    ports:
      - ${GATEWAY_PORT}:80
      # - '443:443'
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config
    depends_on: -back
      -front

volumes:
  caddy_data:
    external: true
  caddy_config:
